# Generated by Django 4.2.7 on 2023-11-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'CURD'), ('ML', 'MILK'), ('LS', 'LASSI'), ('PN', 'PANEER'), ('MS', 'MILK SHAKE'), ('GH', 'GHEE'), ('CZ', 'CHEESE'), ('IC', 'ICE-CREAM'), ('KF', 'KULFI')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('kerala', 'kerala'), ('karnataka', 'karnataka'), ('maharashtra', 'maharashtra'), ('mizhoram', 'mizhoram'), ('thamilnadu', 'thamilnadu'), ('Andra pradesh', 'Andra pradesh')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
